version: "3.7"

services:

  node:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DATABASE: delivery
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: delivery
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "delivery" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data:
    driver: local
  pgdata:
    driver: local
